const express = require("express");
const router = express.Router();
const {getUsers,registerUser,SendOtp,CourseUpdate,SectionDelete,CourseDelete,TopicDelete,ContentUpdate,SectionUpdate,TopicUpdate,AddContent,getOneCourse,AddTopic,AddCourse,AddSection,loginUser,getCourse,ContentDelete} = require("../Controllers/path");
router.route("/users").get(getUsers);
router.route("/register/user").post(registerUser);
router.route("/login/user").post(loginUser);
router.route("/SendOtp").post(SendOtp);
router.route("/course").get(getCourse);
router.route("/add/course").post(AddCourse);
router.route("/add/section").post(AddSection);
router.route("/course/:id").get(getOneCourse);
router.route("/add/section/topic").post(AddTopic);
router.route("/add/content").post(AddContent);
router.route("/course/update").put(CourseUpdate);
router.route("/course/section/update").put(SectionUpdate);
router.route("/course/section/topic/update").put(TopicUpdate);
router.route("/content/update").put(ContentUpdate);
router.route("/content/delete").delete(ContentDelete);
router.route("/course/section/topic/delete").delete(TopicDelete);
router.route("/course/section/delete").delete(SectionDelete);
router.route("/course/delete").delete(CourseDelete);
module.exports = router;