const express = require("express");
const router = express.Router();
const {getUsers,registerUser,SendOtp,CourseUpdate,SectionDelete,CourseDelete,getSingleUser,TopicDelete,ContentUpdate,SectionUpdate,TopicUpdate,AddContent,getOneCourse,AddTopic,AddCourse,AddSection,loginUser,getCourse,ContentDelete} = require("../Controllers/path");
const {AddContentQuiz,AddSectionQuiz,getRandomQuiz,AddCourseQuiz,AddRandomQuiz,getCourseSingleQuiz,getSectionSingleQuiz,getTopicSingleQuiz,getTopicQuiz,getSectionQuiz,GetAllQuiz,GetDailyQuiz,saveResult,getCourseQuiz}  = require("../Controllers/quizPath");
router.route("/users").get(getUsers);
router.route("/users/:id").get(getSingleUser);
router.route("/register/user").post(registerUser);
router.route("/login/user").post(loginUser);
router.route("/SendOtp").post(SendOtp);
router.route("/course").get(getCourse);
router.route("/add/course").post(AddCourse);
router.route("/add/section").post(AddSection);
router.route("/course/:id").get(getOneCourse);
router.route("/add/section/topic").post(AddTopic);
router.route("/add/content").post(AddContent);
router.route("/course/update").put(CourseUpdate);
router.route("/course/section/update").put(SectionUpdate);
router.route("/course/section/topic/update").put(TopicUpdate);
router.route("/content/update").put(ContentUpdate);
router.route("/content/delete").delete(ContentDelete);
router.route("/course/section/topic/delete").delete(TopicDelete);
router.route("/course/section/delete").delete(SectionDelete);
router.route("/course/delete").delete(CourseDelete);
router.route("/add/content/Quiz").post(AddContentQuiz);
router.route("/add/section/Quiz").post(AddSectionQuiz);
router.route("/add/course/Quiz").post(AddCourseQuiz);
router.route("/AllQuiz").get(GetAllQuiz);
router.route("/dailyQuiz").get(GetDailyQuiz);
router.route("/saveResult/:id").post(saveResult);
router.route("/courseQuiz/:name").get(getCourseQuiz);
router.route("/courseQuiz/:name/:sectionId").get(getSectionQuiz);
router.route("/courseQuiz/:name/:sectionId/:topicId").get(getTopicQuiz);
router.route("/Quiz/:name/:QuizId/").get(getCourseSingleQuiz); //courseName ~~ name
router.route("/Quiz/:name/:sectionId/:QuizId/").get(getSectionSingleQuiz);
router.route("/Quiz/:name/:sectionId/:topicId/:QuizId/").get(getTopicSingleQuiz);
router.route("/add/randomQuiz").post(AddRandomQuiz);
router.route("/scheduledQuiz").get(getRandomQuiz);
module.exports = router;